config/routes.rb
require 'sidekiq/web'
MovieBuddy::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "home#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "sessions#new"
    end
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'    
  end
  
  devise_for :users, :controllers => {
                        :omniauth_callbacks => "users/omniauth_callbacks",
                        :sessions => "sessions",
                        :registrations => "registrations"
                      }

  resources :movies do
    resources :reviews
    member do
      get 'vote'
    end
  end

  resources :tv_shows

  resources :updates, :only => [:create, :index] do
    resources :comments, :only => [:create]
    member do
      get 'vote'
    end
  end

  get 'users' => 'users#index', as: :all_users
  get 'users/:id' => 'users#show', as: :user_show
  get 'users/:id/movies' => 'users#movies', as: :user_movies
  get 'users/:id/following' => 'users#following', as: :user_follows
  get 'users/:id/followers' => 'users#followers', as: :user_followers
  get 'users/:id/activity' => 'users#activity'
  get 'users/:id/tv_shows' => 'users#tv_shows', as: :user_tv_shows
  get 'password/edit' => 'users#edit', as: :password_edit
  patch 'password/edit' => 'users#update_password'
  get 'settings/sharing' => 'users#sharing', as: :user_sharing
  delete 'settings/sharing' => 'authentications#destroy', as: :delete_auth
  get 'updates/more' => 'updates#more'

  get '/follow' => 'users#follow', as: :user_follow
  get '/unfollow' => 'users#unfollow', as: :user_unfollow

  

end

app/models/user.rb
class User < ActiveRecord::Base
	include PublicActivity::Common

	extend FriendlyId
  	friendly_id :slug_name, use: :slugged

	# custom method for friendly id
	def slug_name
		"#{rand(36**5).to_s(36)}-#{name}"
	end
	
	acts_as_voter 
	acts_as_followable
	acts_as_follower

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable, :omniauthable

	has_many :authentications, dependent: :destroy	
	has_many :movies, dependent: :destroy
	has_many :comments, through: :movies
	has_many :updates, dependent: :destroy
	has_many :comments, through: :updates	
	has_many :tv_shows, dependent: :destroy

	has_attached_file :avator, :styles => { :small => "32x32#", :thumb => "64x64#", :profile => "290x290#", :medium => "210x180#" },
		:url => "/assets/users/:id/:style/:basename.:extension",
	  	:path => ":rails_root/public/assets/users/:id/:style/:basename.:extension",
	  	:default_url => ':style_default.png'

	validates_presence_of :name
	validates_attachment_size :avator, :less_than => 5.megabytes
	validates_attachment_content_type :avator, :content_type => ['image/jpeg', 'image/png','image/jpg']


	def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
		
		if signed_in_resource == nil
			authentication = Authentication.where(:provider => auth.provider, :uid => auth.uid).first
			user = authentication.user unless authentication.nil?
			unless user.nil?
				user.authentications.find_by_uid(auth.uid).update_attributes(provider:auth.provider,
	                uid:auth.uid,
	                token: auth.credentials.token,
	                )
			  	return user
			else
				unless  Authentication.where(:email => auth.info.email).first.nil?
					registered_user = Authentication.where(:email => auth.info.email).first.user
				else
					registered_user = User.where(:email => auth.info.email).first
				end

				if registered_user
					return registered_user
				else
					user = User.create(name:auth.extra.raw_info.name,
					    email:auth.info.email,
					    avator: URI.parse(auth.info.image),
					    password: Devise.friendly_token[0,20],
					    )
					user.authentications.create(username:auth.extra.raw_info.name,
						provider:auth.provider,
					    uid:auth.uid,
					    token: auth.credentials.token,	
					    social_url: auth.extra.raw_info.link			    
					    )
					return user
				end
			   
			end
		else
			signed_in_resource.authentications.create(username:auth.extra.raw_info.name,
					 provider:auth.provider,
				    uid:auth.uid,
				    token: auth.credentials.token,
				    email:auth.info.email,
				    social_url: auth.extra.raw_info.link
				    )
		    return signed_in_resource		
		end
	end

	def self.find_for_twitter_oauth(auth, signed_in_resource=nil) 
		if signed_in_resource == nil
			authentication = Authentication.where(:provider => auth.provider, :uid => auth.uid).first
			user = authentication.user unless authentication.nil?
			unless user.nil?
	    		return user
	  		else
	  			unless Authentication.where(:email => auth.info.nickname + "@twitter.com").first.nil?
	  				registered_user = Authentication.where(:email => auth.info.nickname + "@twitter.com").first.user
	  			else
	    			registered_user = User.where(:email => auth.info.nickname + "@twitter.com").first
	    		end

	    		if registered_user
	    	  		return registered_user
			    else
			    	user = User.create(name:auth.info.name,
			        	email:auth.info.nickname + "@twitter.com",	        
			        	avator: URI.parse(auth.info.image),
			        	password: Devise.friendly_token[0,20],
			      	)
			      	user.authentications.create(username:auth.info.nickname  ,
			      		provider:auth.provider,
			        	uid:auth.uid,
			        	token: auth.credentials.token,
			        	social_url: auth.info.urls.Twitter,
			        )
			      	return user
			    end
			end	
		else
			signed_in_resource.authentications.create(username:auth.info.nickname  ,
						provider:auth.provider,
			        	uid:auth.uid,
			        	token: auth.credentials.token,
			        	email:auth.info.nickname + "@twitter.com",
			        	social_url: auth.info.urls.Twitter,
			        	)
			return signed_in_resource
		end
	end

	def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
		data = access_token.info
		if signed_in_resource == nil
			authentication = Authentication.where(:provider => access_token.provider, :uid => access_token.uid).first
			user = authentication.user unless authentication.nil?
			unless user.nil?
				return user
			else
				unless Authentication.where(:email => access_token.info.email).first.nil?
					registered_user = Authentication.where(:email => access_token.info.email).first.user
				else
					registered_user = User.where(:email => access_token.info.email).first 
				end

				if registered_user
					return registered_user
				else
					user = User.create(name: data["name"],					
						email: data["email"],					
						avator: URI.parse(data["image"]),
						password: Devise.friendly_token[0,20],
					)
					user.authentications.create(username: data["name"],	
						provider:access_token.provider,
				        uid: access_token.uid ,
				        token: access_token.credentials.token,	
				        social_url: access_token.extra.raw_info.link,			        
				        )
					return user
				end
	    	end
	    else
	    	signed_in_resource.authentications.create(username: data["name"],	
	    			provider:access_token.provider,
	    	        uid: access_token.uid ,
	    	        token: access_token.credentials.token,
	    	        email: data["email"],
	    	        social_url: access_token.extra.raw_info.link,	
	    	        )
	    	return signed_in_resource			
		end
	end

	def self.search(query)
		conditions = <<-EOS
					    	to_tsvector('english', name) @@ to_tsquery('english', ?)
					  	EOS
	  	where(conditions, query + ':*')
	end

	def facebook
		auth = self.authentications.find_by provider: "facebook"
		Koala::Facebook::API.new(auth.token)
	end

	def granted_permission?
		facebook.get_connections("me","permissions")[0]['publish_stream'].to_i  == 1 ? true : false 
	end

	def connected_facebook?
		self.authentications.where(provider: "facebook").first.present?
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      if current_user
        gflash :success => {:title => "Great!", :value => "Successfully connected Facebook"}
        redirect_to request.referer
      else
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      end
      gflash :success => "Successfully Authenticated from Facebook" if is_navigational_format?

    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    auth = env["omniauth.auth"]
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      if current_user
        gflash :success => {:title => "Great!", :value => "Successfully connected Twitter"}
        redirect_to request.referer
      else
        gflash :success => "Successfully Authenticated from Twitter"
        sign_in_and_redirect @user, :event => :authentication
      end
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2     
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      if current_user
        gflash :success => {:title => "Great!", :value => "Successfully connected Google"}
        redirect_to request.referer
      else
        gflash :success => "Successfully Authenticated from Google"
        sign_in_and_redirect @user, :event => :authentication
      end
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	def index
		if params[:q]
			@users = User.search(params[:q])
		elsif params[:search]
			results = User.search(params[:search])
			@users = Kaminari.paginate_array(results).page(params[:page]).per(8)				
		else
			@users = User.where('id != ?', current_user.id).page(params[:page]).per(8)
		end
		respond_to do |format|
		    format.html
		    format.json do
		      render :json => custom_json_for(@users)
		    end
		end
	end

	def show
		@user = User.friendly.find(params[:id])
		@recent_movies = @user.movies.first(6)
		@recent_shows = @user.tv_shows.first(6)
		@tmdb = Tmdb.new
		@activities = PublicActivity::Activity.order('created_at desc').where(owner_id: @user.id, owner_type: "User").limit(5)
		
		# for social networks
		@connected_twitter = @user.authentications.where(:provider => "twitter")
		@connected_facebook = @user.authentications.where(:provider => "facebook")
		@connected_google = @user.authentications.where(:provider => "google_oauth2")
	end

	def edit
		@user = current_user
	end

	def update_password
	    @user = User.find(current_user.id)
	    if @user.update_with_password(user_params)
	      # Sign in the user by passing validation in case his password changed
	      gflash :success => { :value => "Your password was successfully updated", :time => 3000 }
	      sign_in @user, :bypass => true
	      redirect_to root_path
	    else
	      render "edit"
	    end
  	end

	def movies
		@user = User.friendly.find(params[:id])
		@genres = user_movie_genres(@user)
		if current_user == @user
			redirect_to movies_path
		else
			@movies = @user.movies.page(params[:page]).per(8)
			@tmdb = Tmdb.new
		end
	end

	def tv_shows
		@user = User.friendly.find(params[:id])
		if current_user == @user
			redirect_to tv_shows_path
		else
			@tv_shows = @user.tv_shows.page(params[:page]).per(8)
			@tmdb = Tmdb.new
		end
	end

	def following
		@user = User.friendly.find(params[:id])
		@following = Kaminari.paginate_array(@user.all_following).page(params[:page]).per(8)
	end

	def followers
		@user = User.friendly.find(params[:id])
		@followers = Kaminari.paginate_array(@user.followers).page(params[:page]).per(8)
	end

	def follow
		@user = User.friendly.find(params[:id])
		url = request.referer
		if current_user.follow(@user)
			ActivityWorker.perform_async("User", @user.id, current_user.id, { key: "user.follow", action: "follow"} )
			MailerWorker.perform_async(@user.id, "userFollow", { actor_id: current_user.id })

			gflash :success => { :value => "successfully followed #{@user.name}", :time => 3000, :title => "Awesome!!" }
			respond_to do |format|
				format.html { redirect_to url }
				format.js
			end
		end
	end

	def unfollow
		@user = User.friendly.find(params[:id])
		url = request.referer
		if current_user.stop_following(@user)
			#ActivityWorker.perform_async("User", @user.id, current_user.id, key = "user.unfollow", action = "unfollow")

			gflash :warning => { :value => "successfully unfollowed #{@user.name}", :title => "Ooops!" }
			respond_to do |format|
				format.html { redirect_to url}
				format.js
			end
		end
	end

	def sharing
		@connected_twitter = current_user.authentications.where(:provider => "twitter")
		@connected_facebook = current_user.authentications.where(:provider => "facebook")
		@connected_google = current_user.authentications.where(:provider => "google_oauth2")
	end

	def activity
		@activity_id = params[:activity_id]
		@user = User.friendly.find(params[:id])
		@tmdb = Tmdb.new
		@activities = PublicActivity::Activity.where("owner_id = ? and owner_type = ? and id < ?", @user.id, "User",@activity_id).order('created_at desc').limit(5)
		respond_to do |format|
			format.js
		end
	end

	private

	def user_params
		params.required(:user).permit(:password, :password_confirmation, :current_password)
	end

	def custom_json_for(value)
	  list = value.map do |user|
	    { :permalink => user_show_path(user),
	      :image => user.avator.url(:thumb) == "thumb_default.png" ? ActionController::Base.helpers.asset_path('thumb_default.png') : user.avator.url(:thumb),
	      :title => user.name
	    }
	  end
	  list.to_json
	end
end

app/views/users/_activities.html.erb
<% activities.each do |activity| %>
    <tr data-id="<%= activity.id %>">
        <td width="70%">
            <%= render :partial => 'activity_icon', locals: { activity: activity } %>
            <%= activity.owner.name.split(" ").first %>
            <% if activity.trackable_type == "Review"%>
                reviewed a <%= link_to "Movie", movie_path(activity.trackable.movie), class: "home" %>

                <blockquote style="margin-top: 15px;">
                    <p><%= activity.trackable.body %></p>
                    <small>
                        <cite title="Source Title">
                            <%= activity.trackable.movie.title %>
                        </cite>
                    </small>
                </blockquote>
        </td>

        <td align="right">
            <%= link_to image_tag(@tmdb.imageUrl('poster', 'w92',activity.trackable.movie.poster)), movie_path(activity.trackable.movie) %>

            <% elsif activity.trackable_type == "Movie" %>
                <% if activity.key == "movie.create" %>
                    added a new <%= link_to "Movie", movie_path(activity.trackable), class: "home" %> to his collection
                <% elsif activity.key == "movie.like" %>
                    likes a <%= link_to "Movie", movie_path(activity.trackable), class: "home" %>
                <% elsif activity.key == "movie.dislike" %>
                    dislikes a <%= link_to "Movie", movie_path(activity.trackable), class: "home" %>
                <% end %>

            <blockquote style="margin-top: 15px;">
                <p><%= activity.trackable.title %></p>
            </blockquote>
        </td>

        <td align="right">
            <%= link_to image_tag(@tmdb.imageUrl('poster', 'w92',activity.trackable.poster)), movie_path(activity.trackable) %>
        
            <% elsif activity.trackable_type == "Update" %>
                updated his status
                                      
        </td>
        <td>
            <%= activity.trackable.content %>
        </td>

        <% elsif activity.trackable_type == "User" %>     

            <%= activity.key == "user.follow" ? "followed" : "unfollowed" %>
            <%= link_to activity.trackable.name, user_show_path(activity.trackable), class: "home" %>

            <td align="right">
                <%= link_to image_tag(activity.trackable.avator.url(:thumb)), user_show_path(activity.trackable) %>                          
            </td>
        <% elsif activity.trackable_type == "Comment" %>     
            commented on an <%= link_to "update", '#', class: "home" %>

            <blockquote style="margin-top: 15px;">
                <p><%= raw(activity.trackable.update.content) %></p>
                <% unless activity.trackable.update.movie.equal?(0) %>
                    <p><%= image_tag(@tmdb.imageUrl('poster','w92', Movie.find(activity.trackable.update.movie).poster)) %></p>
                <% end %>
                <small>
                    <cite title="Source Title">
                        update by: <%= activity.trackable.update.user.name %>
                    </cite>
                </small>
            </blockquote>
            <td align="right">
                <%= activity.trackable.content %>                          
            </td>
        <% elsif activity.trackable_type == "TvShow" %>     
                added a new <%= link_to "tv show", tv_show_path(activity.trackable), class: "home" %> to his collection

                <blockquote style="margin-top: 15px;">
                    <p><%= activity.trackable.name %></p>
                </blockquote>
                <td align="right">
                     <%= link_to image_tag(@tmdb.imageUrl('poster', 'w92',activity.trackable.poster)), tv_show_path(activity.trackable) %>                          
                </td>
        <% end %>  
    </tr>
<% end %>

app/views/users/_follow_stats.html.erb
<%  unless current_user == @user %>
    <% if current_user.following?(@user) %>
        <%= link_to "Un Follow" ,user_unfollow_path(id: @user.id), class: "btn btn-flat flat-danger btn-lg btn-block follow-unfollow", id: @user.id %>
    <% else %>
        <%= link_to "Follow" ,user_follow_path(id: @user.id), class: "btn btn-flat flat-info btn-lg btn-block follow-unfollow", id: @user.id %>
    <% end %> 
<% else %>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-flat flat-info btn-lg btn-block " %>
<% end %> 

app/views/users/_user.html.erb
<div class="col-xs-6 col-sm-4 col-md-3 portfolio-item-wrapper">
    <div class="portfolio-item">
        <div class="portfolio-thumb">
            <%= link_to (image_tag user.avator.url(:medium), class: "img-responsive"),  user_show_path(user) %>
        </div>
        <div class="portfolio-content">
            <h5><%= user.name %></h5>
            <span><%= user.movies.count %> Movies</span><br /><br />
            <% unless current_user == user %>
                <% if current_user.following?(user) %>
                    <%= link_to "unfollow" ,user_unfollow_path(id: user.id), class: "btn btn-flat flat-danger btn-sm btn-block follow-unfollow", id: user.id %>
                <% else %>
                    <%= link_to "follow" ,user_follow_path(id: user.id), class: "btn btn-flat flat-info btn-sm btn-block follow-unfollow", id: user.id %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/_user_stats.html.erb
<hr />
<div class="row">
	<div class="col-xs-6 col-sm-4 col-md-4">
		<h4>
			<span class="count"><%= user.movies.count %></span> <%= link_to "Movies", user_movies_path(user) %>
		</h4>
	</div>
	<div class="col-xs-6 col-sm-4 col-md-4">
		<h4>
			<span class="count"><%= user.followers_count %></span> <%= link_to "Followers", user_followers_path(user) %>
		</h4>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4">
		<h4>
			<span class="count"><%= user.follow_count %></span> <%= link_to "Following", user_follows_path(user) %>
		</h4>
	</div>
</div>
<hr />

app/views/users/edit.html.erb
<% title "Change Password" %>

<section id="page-title-wrapper" class="section page-title-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 page-title">
              <h4>Edit Profile</h4>
            </div>
            <!-- /.page-title -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<section id="item-content-wrapper" class="section">
  <div class="container">
    <div class="row">
    <div class="col-md-4">
        <%= render 'shared/edit_links' %>
    </div>
      <div class="col-md-8 v-ruler-2">

                  <% if @user.errors.any? %>
            <div class="alert alert-danger alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <strong>Oh noo!</strong>
              <% @user.errors.full_messages.each do |msg| %>
              <p><%= msg %></p>
            <% end %>
          </div>
          <% end %>
          <legend>Change your password</legend>
          <%= form_for(@user, :url => password_edit_path, :html => {:class => 'form-horizontal'} ) do |f| %>

            <div class="form-group">
              <%= f.label :current_password, :class =>"col-md-3" %>

              <div class="col-md-7">
                <%= f.password_field :current_password, :class => "form-control" %>
              </div> <!-- /.col -->

            </div> <!-- /.form-group -->


            <div class="form-group">
              <%= f.label "New Password", :class => "col-md-3" %> 

              <div class="col-md-7">
              <%= f.password_field :password, :autocomplete => "off", :class => "form-control" %>
              </div> <!-- /.col -->

            </div> <!-- /.form-group -->


            <div class="form-group">
              <%= f.label "Confirm Password", :class =>"col-md-3" %>

              <div class="col-md-7">
              <%= f.password_field :password_confirmation, :class => "form-control" %>
              </div> <!-- /.col -->

            </div> <!-- /.form-group -->

            <div class="form-group">

              <div class="col-md-7 col-md-push-3">
              <%= f.submit "Update Password", :class => "btn btn-primary" %>
              <!-- /.col -->

             </div> <!-- /.form-group -->

          <% end %>
        </div>
      </div>


  </div>
</section>

app/views/users/show.html.erb
<% title "#{@user.name}'s Profile" %>

<% content_for(:meta_tags) do %>
    <meta property="og:title" content="<%= @user.name %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.url %>" />
    <meta property="og:image" content="<%= @user.avator.url(:profile) %>" />
    <meta name="description" content="<%= @user.name %>">
<% end %>

<section id="page-title-wrapper" class="section page-title-wrapper clearfix">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 page-title">
            	<% if current_user == @user %>
                	<h4>My Profile</h4>
                <% else %>
                	<h4><%= @user.name %>'s Profile</h4>
                <% end %>
            </div>
            <!-- /.page-title -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<section id="item-content-wrapper" class="section">
    <div class="container">
        <div class="row">
                    <div class="col-md-4">
                        <div class="team-member-wrapper">
                        <div class="team-member">
                            <div class="team-member-thumb">
                                 <%= image_tag @user.avator.url(:profile), class: "img-responsive" %>

                                <div class="overlay"></div>                                
                                <ul class="member-social">
                                    <li><%= link_to raw('<i class="icon-facebook"></i>'), @connected_facebook.any? ? @connected_facebook.first.social_url : "#" %></li>
                                    <li><%= link_to raw('<i class="icon-twitter"></i>'), @connected_twitter.any? ? @connected_twitter.first.social_url : "#"  %></li>
                                    <li><%= link_to raw('<i class="icon-google-plus"></i>'), @connected_google.any? ? @connected_google.first.social_url : "#" %></li>
                                    <li><%= link_to raw('<i class="icon-zoom-in"></i>'),@user.avator.url, rel: "prettyPhoto" %></li>
                                </ul>
                            </div>
                            <div class="team-member-info">
                                <h5><%= @user.name %></h5>
                            </div>
                        </div>

                    </div>
                        <div class="wrapper-1">
                            <div class="row">
                            <div class="col-md-12 col-sm-6">
                                <div class="wrapper-1">
                                <h5 class="subpage-title">Followers 
                                    <small class="pull-right"><%= link_to "see all", user_followers_path(@user), class: "see-all" %></small>
                                </h5>
                                <% for user in @user.followers.shuffle[0..7] %>
                                    <%= link_to image_tag(user.avator.url(:small), alt: user.name, title: user.name, class: "update-img user"), user_show_path(user) %>
                                <% end %>
                            </div>

                            </div>
                            
                            <div class="col-md-12 col-sm-6">
                                <div class="wrapper-1">
                                <h5 class="subpage-title">Following 
                                    <small class="pull-right"><%= link_to "see all", user_follows_path(@user), class: "see-all" %></small>
                                </h5>
                                <% for user in @user.follows.shuffle[0..7] %>
                                    <%= link_to image_tag(user.followable.avator.url(:small), alt: user.followable.name, title: user.followable.name,  class: "update-img user"), user_show_path(user.followable) %>
                                <% end %>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-8">

                    
                        <div class="wrapper-1">
                            

                            <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-6 v-ruler-1 profile-stats">
                                <span><%= link_to @user.movies.count, user_movies_path(@user) %></span>Movies
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 v-ruler-1 profile-stats">
                                 <span><%= link_to @user.tv_shows.count, user_tv_shows_path(@user) %></span>TV Shows
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 profile-stats">
                                 <span><%= link_to @user.followers.count, user_followers_path(@user) %></span>Followers
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-6 v-ruler-2 profile-stats">
                                 <span><%= link_to @user.follows.count, user_follows_path(@user) %></span>Following
                            </div>
                        </div>
                                                    <div class="clearfix"></div>
                            <hr class="polished">

                </div>
                
                <div class="row wrapper-1">
                    <div class="col-md-12">
                        <h5 class="subpage-title">Recent Movies 
                            <small class="pull-right"><%= link_to "see all", user_movies_path(@user), class: "see-all" %></small>
                        </h5>
                    </div>
                                                            <% if @recent_movies.any? %>
                                        <%= render :partial => 'shared/thumbnails', locals: { collection: @recent_movies, size: "w92", resource: "Movie" } %>
                                    <% else %>
                                    <div class="col-md-12">
                                        <%= current_user == @user ? "Its lonely here....please add some movies" : "#{@user.name} hasn't added any movies yet" %>
                                    </div>
                                    <% end %>



                </div>

                <div class="row">
                    <div class="col-md-12">
                        <h5 class="subpage-title">Recent Tv Shows
                            <small class="pull-right"><%= link_to "see all", user_tv_shows_path(@user), class: "see-all" %></small>
                        </h5>
                    </div>

                                                            <% if @recent_shows.any? %>
                                        <%= render :partial => 'shared/thumbnails', locals: { collection: @recent_shows, size: "w92", resource: "TvShow" } %>
                                    <% else %>
                                    <div class="col-md-12">
                                        <%= current_user == @user ? "Its lonely here....please add some shows" : "#{@user.name} hasn't added any shows yet" %>
                                    </div>
                                    <% end %>


                </div>
                <div class="wrapper-1">
                <div class="row">
                                            <div class="col-md-12">
                            <h5 class="subpage-title">Recent Activity</h5>
                            <% if current_user.following?(@user) || @user == current_user %>
                                <% if @activities.any? %>
                                    <table class="table recent-activity">
                                        <tbody>
                                            <%= render :partial => 'activities', locals: { activities: @activities } %>
                                        </tbody>
                                    </table>
                                    <%= link_to "More", "#", class: "btn btn-flat flat-default btn-bordered btn-lg btn-block", id: "more-activity"  %>
                                    <div class="more" style="text-align: center;"></div>
                                <% else %>
                                    <div class="col-md-12" style="margin-bottom: 40px;">
                                        <p>No activity found....</p>
                                    </div>
                                <% end %>
                            <% else %>
                                <p class="post-title">Follow <%= @user.name %> to see his/her recent activity </p>
                            <% end %>                            
                        </div>
                </div>
            </div>


                    </div>
        </div>
    </div>
</section>