config/routes.rb
require 'sidekiq/web'
MovieBuddy::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "home#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "sessions#new"
    end
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'    
  end
  
  devise_for :users, :controllers => {
                        :omniauth_callbacks => "users/omniauth_callbacks",
                        :sessions => "sessions",
                        :registrations => "registrations"
                      }

  resources :movies do
    resources :reviews
    member do
      get 'vote'
    end
  end

  resources :tv_shows

  resources :updates, :only => [:create, :index] do
    resources :comments, :only => [:create]
    member do
      get 'vote'
    end
  end

  get 'users' => 'users#index', as: :all_users
  get 'users/:id' => 'users#show', as: :user_show
  get 'users/:id/movies' => 'users#movies', as: :user_movies
  get 'users/:id/following' => 'users#following', as: :user_follows
  get 'users/:id/followers' => 'users#followers', as: :user_followers
  get 'users/:id/activity' => 'users#activity'
  get 'users/:id/tv_shows' => 'users#tv_shows', as: :user_tv_shows
  get 'password/edit' => 'users#edit', as: :password_edit
  patch 'password/edit' => 'users#update_password'
  get 'settings/sharing' => 'users#sharing', as: :user_sharing
  delete 'settings/sharing' => 'authentications#destroy', as: :delete_auth
  get 'updates/more' => 'updates#more'

  get '/follow' => 'users#follow', as: :user_follow
  get '/unfollow' => 'users#unfollow', as: :user_unfollow

  

end

app/views/shared/_edit_links.html.erb
<ul class="nav nav-pills  nav-stacked">
    <li class="<%= controller_name == "registrations" && action_name == "edit" ? "active" : "" %>">
       <%= link_to raw('<i class="icon-user"></i> &nbsp;&nbsp; Profile Settings'), edit_user_registration_path %>
    </li>
    <li class="<%= controller_name == "users" && action_name == "edit" ? "active" : "" %>">
      <%= link_to raw('<i class="icon-key"></i> &nbsp;&nbsp; Change Password'), password_edit_path %>
    </li>
    <li class="<%= controller_name == "users" && action_name == "sharing" ? "active" : "" %>">
       <%= link_to raw('<i class="icon-globe"></i> &nbsp;&nbsp; Sharing with Other Networks'), user_sharing_path %>
    </li>
</ul>

app/views/shared/_genres.html.erb
<h5 class="subpage-title">Genres</h5>
 <ul class="portfolio-filter nav nav-pills">
	<li class="active"><a href="#" data-filter="*">All</a></li>
        <% genres.each do |genre| %>
	        <% if genre.split.size > 1 %>
	            <li class=""><a href="#" data-filter=".<%= genre.split.join(".").downcase %>"><%= genre.capitalize %></a> </li>
	        <% else %>
	            <li class=""><a href="#" data-filter=".<%= genre.downcase %>"><%= genre.capitalize %></a></li>
	        <% end %>
    <% end %>
</ul>

app/views/shared/_google_ads.html.erb
<div id="google-ads-1"></div>
 
<script type="text/javascript"> 
 
    /* Calculate the width of available ad space */
    ad = document.getElementById('google-ads-1');
 
    if (ad.getBoundingClientRect().width) {
        adWidth = ad.getBoundingClientRect().width; // for modern browsers 
    } else {
        adWidth = ad.offsetWidth; // for old IE 
    }
 
    /* Replace ca-pub-XXX with your AdSense Publisher ID */ 
    google_ad_client = "ca-pub-0765173663573649";
 
    /* Replace 1234567890 with the AdSense Ad Slot ID */ 
    google_ad_slot = "6935021063";
  
    /* Do not change anything after this line */
    if ( adWidth >= 728 )
      google_ad_size = ["728", "90"];  /* Leaderboard 728x90 */
    else if ( adWidth >= 468 )
      google_ad_size = ["468", "60"];  /* Banner (468 x 60) */
    else if ( adWidth >= 336 )
      google_ad_size = ["336", "280"]; /* Large Rectangle (336 x 280) */
    else if ( adWidth >= 300 )
      google_ad_size = ["300", "250"]; /* Medium Rectangle (300 x 250) */
    else if ( adWidth >= 250 )
      google_ad_size = ["250", "250"]; /* Square (250 x 250) */
    else if ( adWidth >= 200 )
      google_ad_size = ["200", "200"]; /* Small Square (200 x 200) */
    else if ( adWidth >= 180 )
      google_ad_size = ["180", "150"]; /* Small Rectangle (180 x 150) */
    else
      google_ad_size = ["125", "125"]; /* Button (125 x 125) */
 
    document.write (
     '<ins class="adsbygoogle" style="display:inline-block;width:' 
      + google_ad_size[0] + 'px;height:' 
      + google_ad_size[1] + 'px" data-ad-client="' 
      + google_ad_client + '" data-ad-slot="' 
      + google_ad_slot + '"></ins>'
    );
  
    (adsbygoogle = window.adsbygoogle || []).push({});
 
</script>
 
<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
</script>

app/views/shared/_google_ads_1.html.erb
<div id="google-ads-1"></div>
 
<script type="text/javascript"> 
 
    /* Calculate the width of available ad space */
    ad = document.getElementById('google-ads-1');
 
    if (ad.getBoundingClientRect().width) {
        adWidth = ad.getBoundingClientRect().width; // for modern browsers 
    } else {
        adWidth = ad.offsetWidth; // for old IE 
    }
 
    /* Replace ca-pub-XXX with your AdSense Publisher ID */ 
    google_ad_client = "ca-pub-0765173663573649";
 
    /* Replace 1234567890 with the AdSense Ad Slot ID */ 
    google_ad_slot = "6935021063";
  
    /* Do not change anything after this line */
    if ( adWidth >= 728 )
      google_ad_size = ["728", "90"];  /* Leaderboard 728x90 */
    else if ( adWidth >= 468 )
      google_ad_size = ["468", "60"];  /* Banner (468 x 60) */
    else if ( adWidth >= 336 )
      google_ad_size = ["336", "280"]; /* Large Rectangle (336 x 280) */
    else if ( adWidth >= 300 )
      google_ad_size = ["300", "250"]; /* Medium Rectangle (300 x 250) */
    else if ( adWidth >= 250 )
      google_ad_size = ["250", "250"]; /* Square (250 x 250) */
    else if ( adWidth >= 200 )
      google_ad_size = ["200", "200"]; /* Small Square (200 x 200) */
    else if ( adWidth >= 180 )
      google_ad_size = ["180", "150"]; /* Small Rectangle (180 x 150) */
    else
      google_ad_size = ["125", "125"]; /* Button (125 x 125) */
 
    document.write (
     '<ins class="adsbygoogle" style="display:inline-block;width:' 
      + google_ad_size[0] + 'px;height:' 
      + google_ad_size[1] + 'px" data-ad-client="' 
      + google_ad_client + '" data-ad-slot="' 
      + google_ad_slot + '"></ins>'
    );
  
    (adsbygoogle = window.adsbygoogle || []).push({});
 
</script>
 
<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
</script>

app/views/shared/_recent_movies.html.erb
<section id="recent-works" class="section <%= controller_name == "users" ? "colored-wrapper": "" %>">
    <div class="container wrapper-2">
        <h5 class="subpage-title">
            <span><%= controller_name == "home" ? "Upcoming Movies" : "Recent Movies" %></span>
            <!-- Controls -->
            <span id="portfolio-next" class="next black">
                <i class="icon-angle-right"></i>
            </span>
            <span id="portfolio-prev" class="prev black">
                <i class="icon-angle-left"></i>
            </span>
        </h5>
        <div class="row">
            <div id="<%= controller_name == "home" ? "caroufredsel-portfolio-container-home" : "caroufredsel-portfolio-container"%>">
                
                <%= render :partial => 'shared/thumbnails', locals: { collection: movies, size: size, resource: "Movie" } %>
                <!-- /.portfolio-item-wrapper -->
            </div>
            <!-- /.caroufredsel-portfolio-container -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

app/views/shared/_search_form.html.erb
<%= form_tag(movies_path, method: :get, id: "#{ controller_name == "home" || controller_name == "movies" && action_name == "show" ? "" : "movie_search"}") do  %>
	<div class="form-group">
		<%= text_field_tag :q, params[:q], class: "form-control", placeholder: "Search for movies to add" %>
		<button type="submit" id="search-btn" class="btn"><i class="icon-search"></i></button>
	</div>
<% end %>

app/views/shared/_social_links.html.erb
<div class="col-md-12">
	<% link_to image_tag("transparent.gif", class: "signin-facebook"), user_omniauth_authorize_path(:facebook) %>
	<%= link_to "#{ controller_name == 'registrations' ? 'Sign up' : 'Log in'} with facebook", user_omniauth_authorize_path(:facebook), class: "button-facebook" %>
</div>

<div class="col-md-12">
	<% link_to image_tag("transparent.gif", class: "signin-twitter"), user_omniauth_authorize_path(:twitter) %>
	<%= link_to "#{ controller_name == 'registrations' ? 'Sign up' : 'Log in'} with twitter", user_omniauth_authorize_path(:twitter), class: "button-twitter" %>
</div>

<div class="col-md-12">
	<% link_to image_tag("transparent.gif", class: "signin-google"), user_omniauth_authorize_path(:google_oauth2) %>
	<%= link_to "#{ controller_name == 'registrations' ? 'Sign up' : 'Log in'} with Google", user_omniauth_authorize_path(:google_oauth2), class: "button-googleplus" %>
</div>

app/views/shared/_thumbnails.html.erb
<% unless collection.nil? %>
    <% for item in collection %>
<div class="col-xs-3 col-sm-2 <%= controller_name == "home" ? "col-md-3" : "col-md-2" %> portfolio-item-wrapper">
<div class="portfolio-item">
    <div class="portfolio-thumb">
        <% if resource == "Movie" %>
             <%= link_to image_tag(@tmdb.imageUrl('poster',size, item.poster), class: "img-responsive"), movie_path(item) %>
        <% elsif resource == "TvShow" %>
             <%= link_to image_tag(@tmdb.imageUrl('poster',size, item.poster), class: "img-responsive"), tv_show_path(item) %>
        <% end %>
            
        
    </div>
    <% unless current_page?(controller: "home", action: "index") || controller_name == "users" && action_name == "show" %>
    <div class="portfolio-content">
        <h5><%= item.title %></h5>
    </div>
    <% end %>
</div>
</div>
    <% end %>
<% end %>

app/views/shared/_votes_info.html.erb
<div id="vote-info-<%= movie.id %>">
	<div class="col-xs-6 col-md-5">
		<div class="ui-group-buttons">           
		<% if user_signed_in? %>
		  	<% if current_user.voted_how?(movie) == true %>
				<%= link_to raw('I like <span class="icon-thumbs-up"></span>') , '#', class: "btn btn-success disabled vote" %>
				<div class="or"></div>
				<%= link_to raw('I dislike <span class="icon-thumbs-down"></span>'), vote_movie_path(movie, vote: 'down'), class: "btn btn-danger vote" %>
			<% elsif current_user.voted_how?(movie) == false %>
				<%= link_to raw('I like <span class="icon-thumbs-up"></span>') , vote_movie_path(movie, vote: 'up'), class: "btn btn-success vote" %>
				<div class="or"></div>
			 	<%= link_to raw('I dislike <span class="icon-thumbs-down"></span> '), '#', class: "btn btn-danger disabled vote" %>
			 <% else %>		 
			 	<%= link_to raw('I like <span class="icon-thumbs-up"></span>') , vote_movie_path(movie, vote: 'up'), class: "btn btn-success vote" %> 
			 	<div class="or"></div>
			 	<%= link_to raw('I dislike <span class="icon-thumbs-down"></span>'), vote_movie_path(movie, vote: 'down'), class: "btn btn-danger vote" %> 
			<% end %>
		<% else %>
			<%= link_to raw('I like <span class="icon-thumbs-up"></span>') , vote_movie_path(movie, vote: 'up'), class: "btn btn-success" %> 
			<div class="or"></div>
			<%= link_to raw('I dislike <span class="icon-thumbs-down"></span>'), vote_movie_path(movie, vote: 'down'), class: "btn btn-danger" %> 
		<% end %>
		 </div>
	</div>
</div>