config/routes.rb
require 'sidekiq/web'
MovieBuddy::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "home#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "sessions#new"
    end
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'    
  end
  
  devise_for :users, :controllers => {
                        :omniauth_callbacks => "users/omniauth_callbacks",
                        :sessions => "sessions",
                        :registrations => "registrations"
                      }

  resources :movies do
    resources :reviews
    member do
      get 'vote'
    end
  end

  resources :tv_shows

  resources :updates, :only => [:create, :index] do
    resources :comments, :only => [:create]
    member do
      get 'vote'
    end
  end

  get 'users' => 'users#index', as: :all_users
  get 'users/:id' => 'users#show', as: :user_show
  get 'users/:id/movies' => 'users#movies', as: :user_movies
  get 'users/:id/following' => 'users#following', as: :user_follows
  get 'users/:id/followers' => 'users#followers', as: :user_followers
  get 'users/:id/activity' => 'users#activity'
  get 'users/:id/tv_shows' => 'users#tv_shows', as: :user_tv_shows
  get 'password/edit' => 'users#edit', as: :password_edit
  patch 'password/edit' => 'users#update_password'
  get 'settings/sharing' => 'users#sharing', as: :user_sharing
  delete 'settings/sharing' => 'authentications#destroy', as: :delete_auth
  get 'updates/more' => 'updates#more'

  get '/follow' => 'users#follow', as: :user_follow
  get '/unfollow' => 'users#unfollow', as: :user_unfollow

  

end

app/models/update.rb
class Update < ActiveRecord::Base
	include PublicActivity::Common

	scope :from_movies, -> { where('movie != ?', 0) }

	alias_attribute :name, :id
	
	acts_as_voteable
	
	belongs_to :user
	has_many :comments

	validates_presence_of :user_id
	validates_presence_of :content, :if => :not_from_movie?

	default_scope { order('updates.created_at DESC') }

	def not_from_movie?
		self.movie.equal?(0) 
	end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
	before_filter :authenticate_user!
	def index
		following_user_ids = get_following << current_user.id
		@tmdb = Tmdb.new
		@updates = Update.where(user_id: following_user_ids).where("created_at > ?", Time.at(params[:after].to_i + 1))
	end

	def create
		@update = current_user.updates.build(update_params)
		if @update.save
			ActivityWorker.perform_async("Update", @update.id, current_user.id)
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			render 'home/index'
		end
	end

	def vote
		@update = Update.find(params[:id])
		if params[:vote] == 'up'
			current_user.vote_exclusively_for(@update)
		elsif params[:vote] == 'down'
        	current_user.vote_exclusively_against(@update)
		end
		
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def more
		following_user_ids = get_following << current_user.id
		@tmdb = Tmdb.new
		@updates = Update.where(user_id: following_user_ids).where("created_at < ?", Time.at(params[:after].to_i - 1)).limit(5)
	end

	private
		def update_params
			params.require(:update).permit(:content)
		end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_comment_stats.html.erb
<span id="stats-<%= update.id %>">
	<% if current_user.voted_how?(update) == true %>
		<%= link_to "Unlike", vote_update_path(update, :vote => "down"), class: "home like-dislike" %> . <a href="#" class="home com" id="comment-<%= update.id %>">Comment</a>
	<% elsif current_user.voted_how?(update) == false %>
		<%= link_to "Like", vote_update_path(update, :vote => "up"), class: "home like-dislike" %> . <a href="#" class="home com" id="comment-<%= update.id %>">Comment</a> 
	<% else %>
		<%= link_to "Like", vote_update_path(update, :vote => "up"), class: "home like-dislike" %> . <a href="#" class="home com" id="comment-<%= update.id %>">Comment</a> 
	<% end %>
	<span style="margin-left: 5px;"> . 
		<i class="icon-thumbs-up"></i>
			<%= update.votes_for %> &nbsp; . &nbsp;	<i class="icon-comments"></i>
			<%= update.comments.count %>
	</span>
	&nbsp; . &nbsp;
	<span class="comment-date"><%= time_ago_in_words(update.created_at) %> ago</span>
</span>

app/views/updates/_form.html.erb
<% if @update.errors.any? %>
	<div class="alert alert-danger alert-dismissable">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <strong>Oh noo!</strong>
	    <% @update.errors.full_messages.each do |msg| %>
			<p><%= msg %></p>
		<% end %>
	</div>
<% end %>

<%= form_for(@update, :html => {:role => 'form' }) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "What's the latest?...", class: "form-control", rows: 3 %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn btn-flat btn-sm flat-inverse pull-right", id: "post-update" %>
  </div>
<% end %>

app/views/updates/_update.html.erb
<li class="media" data-time="<%= update.created_at.to_i %>">
    <%= link_to image_tag(update.user.avator.url(:thumb), class: "update-img", alt: update.user.name), user_show_path(update.user), class: "pull-left" %>
    <div class="media-body">
        <h5 class="media-heading">
            <%= link_to update.user.name, user_show_path(update.user) %>  
            <small><% if update.movie? %>
                added a new movie
            <% end %> </small>      
        </h5>
        <p><%= raw(update.content) %></p>
                <% unless update.movie.equal?(0) %>
                <% movie = Movie.find(update.movie) %>
            <div class="row updates">
                <div class="col-md-3 col-sm-2 col-xs-6">
                    <%= link_to image_tag(@tmdb.imageUrl('poster', 'w154', movie.poster), class: "img-responsive"), movie_path(movie) %>
                </div>
                <div class="col-md-8 col-sm-10 col-xs-6">
                    <h6><%= link_to movie.title, movie_path(movie), class: "home" %></h6>
              
                <p><%= truncate(movie.overview,  length: 110, omission: '...') %></p>
                </div>
            </div>
        <% end %>

        <%= render :partial => 'updates/comment_stats', locals: {update: update} %>

        <!-- Nested media object -->
        <% @comments = update.comments %>
        <%= render @comments %>

        <div class="media update-comment-form" id="form-<%= update.id %>">
            <%= link_to image_tag(current_user.avator.url(:thumb), width: "50px", height: "50px"), user_show_path(current_user), class: "pull-left" %>
            <div class="media-body">
                <div class="row">
                    <div class="col-md-9">
                        <%= form_for([update, update.comments.build], :html => {:id => "update_" + update.id.to_s }) do |f| %>
                        <%= f.text_area :content, class: "cupdate btn-block", id: "cupdate_" + update.id.to_s %>                       
                    </div>
                    <div class="col-md-3">
                        <%= f.submit "Comment", id: update.id.to_s, class: "update-comment" %>
                    </div>
                    <% end %>
                </div>  
            </div>
        </div>
    </div>                                           
</li>
<hr>

app/views/updates/create.js.erb
var s = jQuery;
s.noConflict();

//prepend new update
s('ul.media-list').prepend('<%= escape_javascript(render(:partial => @update)) %>');

//hide the comment form
s('.media.update-comment-form').hide();

//reset the form
s('#new_update')[0].reset();

app/views/updates/index.js.erb
var s = jQuery;
s.noConflict();

s('<%= escape_javascript(render(:partial => @updates)) %>').hide().prependTo('ul.media-list').fadeIn('slow');

//s('.media.update-comment-form').hide();

app/views/updates/more.js.erb
var s = jQuery;
s.noConflict();

s('ul.media-list').append('<%= escape_javascript(render(:partial => @updates)) %>');

app/views/updates/vote.js.erb
var s = jQuery;
s.noConflict();

s('#stats-<%= @update.id %>').html("<%= escape_javascript(render(:partial => 'updates/comment_stats', locals: {update: @update })) %>");