config/routes.rb
require 'sidekiq/web'
MovieBuddy::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "home#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "sessions#new"
    end
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'    
  end
  
  devise_for :users, :controllers => {
                        :omniauth_callbacks => "users/omniauth_callbacks",
                        :sessions => "sessions",
                        :registrations => "registrations"
                      }

  resources :movies do
    resources :reviews
    member do
      get 'vote'
    end
  end

  resources :tv_shows

  resources :updates, :only => [:create, :index] do
    resources :comments, :only => [:create]
    member do
      get 'vote'
    end
  end

  get 'users' => 'users#index', as: :all_users
  get 'users/:id' => 'users#show', as: :user_show
  get 'users/:id/movies' => 'users#movies', as: :user_movies
  get 'users/:id/following' => 'users#following', as: :user_follows
  get 'users/:id/followers' => 'users#followers', as: :user_followers
  get 'users/:id/activity' => 'users#activity'
  get 'users/:id/tv_shows' => 'users#tv_shows', as: :user_tv_shows
  get 'password/edit' => 'users#edit', as: :password_edit
  patch 'password/edit' => 'users#update_password'
  get 'settings/sharing' => 'users#sharing', as: :user_sharing
  delete 'settings/sharing' => 'authentications#destroy', as: :delete_auth
  get 'updates/more' => 'updates#more'

  get '/follow' => 'users#follow', as: :user_follow
  get '/unfollow' => 'users#unfollow', as: :user_unfollow

  

end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45975849-1', 'moviebuddy.info');
  ga('send', 'pageview');

</script>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Ooops!</h4>
      </div>
      <div class="modal-body">
        <p>Please write something.....</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <%= link_to raw("Movie<span>Buddy</span>"), root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
            	<% if user_signed_in? %>
                <li class="<%= current_page?(controller: 'home') ? "active" : "" %>"><%= link_to raw("<i class='icon-home'></i> Home"), root_path %></li>
                <li class="<%= current_page?(controller: 'users', action: 'index') ? "active" : "" %>"><%= link_to raw("<i class='icon-group'></i> Users"), all_users_path %></li>
            	<li class="<%= current_page?(controller: 'movies') ? "active" : "" %>"><%= link_to raw("<i class='icon-facetime-video'></i> Movies"), movies_path %></li>
                <li class="<%= current_page?(controller: 'tv_shows') ? "active" : "" %>"><%= link_to raw('<i class="icon-desktop"></i> Tv Shows'), tv_shows_path %></li>
                <li class="dropdown <%= (controller_name == 'users' && action_name != 'index') || controller_name =="registrations" ? "active" : "" %>">
                    <a href="#" class="profile-pic dropdown-toggle" data-toggle="dropdown">
                        <%= image_tag(current_user.avator.url(:small), alt: current_user.name, class: "profile-img", width: "32px", height: "32px") + " " + current_user.name.split(" ").first %>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to raw("<i class='icon-user'></i> My Profile"), user_show_path(current_user) %></li>
                        <li><%= link_to raw("Followers <span class='label label-default pull-right'>#{current_user.followers.count}</span>"), user_followers_path(current_user) %> </li>
                        <li><%= link_to raw("Following <span class='label label-default pull-right'>#{current_user.all_following.count}</span>"), user_follows_path(current_user) %></li>
                        <li><%= link_to raw("<i class='icon-cogs'></i> Settings"), edit_user_registration_path %></li>
                        <li><%= link_to(raw("<i class='icon-signout'></i> Log Out"),  destroy_user_session_path, method: :delete)  %></li>
                    </ul>
                </li>       	
            	<% else %>
                <li class="<%= current_page?(controller: 'sessions', action: 'new') ? "active" : "" %>"><%= link_to(raw("<i class='icon-signin'></i> Sign in"), new_user_session_path)  %></li>
					<li class="<%= current_page?(controller: 'registrations', action: 'new') ? "active" : "" %>"><%= link_to(raw("<i class='icon-ticket'></i> Join MovieBuddy"), new_user_registration_path)  %></li> 
                <% end %>                      
            </ul>
            <!-- /.nav -->
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!-- /.navbar -->

app/views/layouts/_skin_chooser.html.erb
<div id="skin-chooser-container" class="skin-chooser-container">
    <a data-toggle="modal" href="#myModal" class="skin-chooser hidden-xs">
        <i class="icon-cog"></i>
    </a>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">CHOOSE COLOR SKIN</h4>
                </div>
                <div class="modal-body">
                    <div class="skins-wrapper">
                        <ul class="list-inline">
                            <li>
                                <div id="color-skin-1" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-2" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-3" class="color-skin active"></div>
                            </li>
                            <li>
                                <div id="color-skin-4" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-5" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-6" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-7" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-8" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-9" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-10" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-11" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-12" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-13" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-14" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-15" class="color-skin"></div>
                            </li>
                            <li>
                                <div id="color-skin-16" class="color-skin"></div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</div>

app/views/layouts/_social_links.html.erb
<ul class="social-links">
    <li>
    	<a href="https://www.facebook.com/Your.Movie.Buddy" target="_blank">
    		<i class="icon-facebook"></i>
    	</a>
    </li>
    <li>
    	<a href="https://plus.google.com/b/115556272872532573673/?hl=en" target="_blank">
    		<i class="icon-google-plus"></i>
    	</a>
    </li>
    <li>
    	<a href="#"><i class="icon-twitter"></i></a>
    </li>
</ul>
<!-- /.social-links -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for?(:title) ? yield(:title) : "MovieBuddy" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="moviebuddy, moviebuddy.info, movies">
    <%= yield(:meta_tags) if content_for?(:meta_tags)  %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag  "application", "http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic|Montserrat:400,700", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= render 'layouts/google_analytics' if Rails.env.production? %>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div id="main-wrapper" class="color-skin-3">
        <header id="header-1" class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-8 header-info-wrapper">
                        <ul class="list-inline">
                            <li class="tagline">
                                <i class="icon-quote-left"></i>
                                One movie is better than two of something else
                                <i class="icon-quote-right"></i>
                            </li>
                        </ul>
                        <!-- /.list-inline -->
                    </div>
                    <!-- /.header-info-wrapper -->
                    <div class="col-xs-12 col-sm-4 social-link-wrapper">
                        <%= render 'layouts/social_links' %>
                    </div>
                    <!-- /.social-link-wrapper -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </header>
        <!-- /.header-1 -->

        <header id="header-2" class="header">
            <%= render "layouts/navigation" %>
        </header>
        <!-- /#header-2 -->

        <%= yield %>

        <footer id="footer-2" class="footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 footer-info-wrapper">
                    <span>MovieBuddy © 2013. Design by <a href="#">Joseph</a></span> <br />  
                    <span>For issues or improvements, raise them at <a href="https://github.com/Joseph-N/moviebuddy/issues/" target="_blank">Github</a></span>                     
                </div>
                <!-- /.footer-info-wrapper -->
                <div class="col-xs-12 col-sm-6 social-link-wrapper">
                    <%= render 'layouts/social_links' %>
                </div>
                <!-- /.social-link-wrapper -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
        </footer>
        <!-- /#footer-2 -->

        <%= render 'layouts/skin_chooser' %>

        <a href="#" id="toTop" style="display: inline;"><span id="toTopHover" style="opacity: 0;"></span>To Top</a>

    </div>
    <%= render 'layouts/modal' %>
    <%= gflash %>
</body>
</html>